### PR TITLE
Clean up interrupted snapshots

### PR DESCRIPTION
**Pull request by plattfot**
Add a new command `--clean` that will remove all snapshots at the receiver location that isn't read only, i.e. incomplete. As all snapper snapshots should be read only if valid. If they are writable that means everything didn't get sent.

### CODE REVIEW

**Comment by mio-19** [comment]
It ask for y/n so I can't use this option on i.e. a systemd service

**Comment by mio-19** [comment]
This command maybe should also clean up incomplete snapshots that only have info and don't have the "snapshot"

**Comment by plattfot** [comment]
> It ask for y/n so I can't use this option on i.e. a systemd service

Good point, I was thinking to have a safeguard similar to delete. But yeah this wont work if you want to automatically clean up. I'll drop the safeguard.

> This command maybe should also clean up incomplete snapshots that only have info and don't have the "snapshot"

Yeah, it should. I'll fix that.

**Comment by plattfot** [comment]
Removed the safeguard and added checks to for missing `info.xml`.

**Comment by plattfot** [comment]
Alright, everything should be good. I had flipped the checks in previous commit which is fixed now.  Then I changed the check for the property to check `!= ro=true` as that should be more robust than checking `!= ro=false`. Since the former should handle if say `snapshot` is just a normal directory.

It will now remove any incomplete snapshot, where incomplete is a snapshot that is either missing `info.xml`, the `snapshot` directory or `snapshot` is not read only.

Please test this out and let me know if anything is missing.

**Comment by mio-19** [comment]
I noticed that not every variable has surrounding quote mark in baksnapperd. They might break if a path contains spaces.

**Comment by plattfot** [comment]
What variables are you specifically thinking of? I lint it with shellcheck and it is usually pretty good at spotting things like this. And only warning I have right now is the `ls` command in `link-latest`.

**Comment by mio-19** [comment]
> What variables are you specifically thinking of? I lint it with shellcheck and it is usually pretty good at spotting things like this. And only warning I have right now is the `ls` command in `link-latest`.

`dest_root=$1`  `if [[ -d $dest_root/$snapshot/snapshot ]]`

**Comment by plattfot** [comment]
> `dest_root=$1` `if [[ -d $dest_root/$snapshot/snapshot ]]`

Yeah, the latter I've missed and seems `shellcheck` did too. The former is just a variable assignment so you do not need to quote anything as bash will not perform any word splitting. Only exception is `"$@"`.

I'll do a pass and quote some variables expansions later today.

**Comment by mio-19** [comment]
I tested it and bash also does not do word splitting for the latter case. It is more a code style thing.

**Comment by plattfot** [comment]
> I tested it and bash also does not do word splitting for the latter case. It is more a code style thing.

Interesting, I would have thought it did that. Probably that's why it did not signal a warning when I checked with shellcheck.

But yeah, agreed that is better to quote that to be consistent with the rest.  See #22 for that.

**Comment by plattfot** [comment]
Any other feedback? Otherwise I'll merge this and release.

**Comment by mio-19** [comment]
> Any other feedback? Otherwise I'll merge this and release.

It looks good to me. But I haven't had time to test this

**Pull request merged**
